twig:
    file_name_pattern: '*.twig'
    globals:
        service_file: '@App\Service\File\FileService'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
when@test:
    twig:
        strict_variables: true
        form_themes: [ 'bootstrap_5_layout.html.twig' ]
