services:
  Silecust\WebShop\Command\Security\User\SuperUserCreateCommand: ~
  Silecust\WebShop\Command\Security\User\CustomerCreateCommand: ~
  Silecust\WebShop\Command\Development\DevDataFixtureForQuickStart: ~