services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Service\Component\UI\Panel\Session\SessionAndMethodChecker:
    public: true

  App\Service\Component\UI\Panel\PanelMainController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Service\Component\UI\Panel\Components\PanelHeadController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Service\Component\UI\Panel\Components\PanelHeaderController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Service\Component\UI\Panel\Components\PanelContentController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Service\Component\UI\Panel\Components\PanelFooterController:
    public: true
    arguments:
      - "@event_dispatcher"

  App\Service\Component\UI\Panel\Components\PanelSideBarController:
    public: true
    arguments:
      - "@event_dispatcher"