services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Service\MasterData\Employee\Mapper\EmployeeDTOMapper: ~

  App\Service\Admin\SideBar\List\PanelSideBarListMapBuilder: ~
  App\Service\Admin\SideBar\List\PanelSideBarListMap: ~
  App\Service\Admin\SideBar\Role\RoleBasedSideBarList: ~
  App\Service\Admin\SideBar\Action\PanelActionListMapBuilder: ~
  App\Service\Admin\SideBar\Action\PanelActionListMap: ~
  App\Service\Admin\Employee\Common\AdminTitle: ~
  App\Service\Admin\Employee\FrameWork\AdminRoutingFromRequestFinder: ~
  App\Service\Admin\Employee\FrameWork\AdminRouteObject: ~
  App\Service\Admin\List\ListGrid: ~
  App\Service\Transaction\Order\Object\OrderObject: ~
  App\Service\Transaction\Order\Admin\Header\OrderStatusValidator: ~
  App\Service\Transaction\Order\IdGeneration\OrderIdStrategy: ~
  App\Service\Transaction\Order\IdGeneration\OrderIdStrategyInterface: ~
  App\Service\Transaction\Order\Header\Shipping\ShippingOrderServiceInterface: ~
  App\Service\Transaction\Order\Header\Shipping\DevShippingCharges: ~
  App\Service\Transaction\Order\Journal\OrderJournalSnapShot: ~
  App\Service\Transaction\Order\Status\OrderStatusTypes: ~
  App\Service\Transaction\Order\SnapShot\SnapshotObject: ~
  App\Service\Transaction\Order\SnapShot\OrderSnapShotCreator: ~
  App\Service\Transaction\Order\PriceObject: ~
  App\Service\Transaction\Order\OrderSave: ~
  App\Service\Transaction\Order\Price\Header\ShippingChargeCalculator: ~
  App\Service\Transaction\Order\Price\Header\HeaderPriceCalculator: ~
  App\Service\Transaction\Order\Price\Item\ItemPriceCalculator: ~
  App\Service\Transaction\Order\OrderRead: ~
  App\Service\Module\WebShop\Admin\File\WebShopFileImageService: ~
  App\Service\Module\WebShop\Admin\File\WebShopFileService: ~
  App\Service\Module\WebShop\Admin\File\WebShopFileDirectoryPathNamer: ~
  App\Service\Module\WebShop\External\Product\ProductListQueryBuilder: ~
  App\Service\Module\WebShop\External\Product\Twig\ProductInProductList: ~
  App\Service\Module\WebShop\External\CheckOut\CheckOutService: ~
  App\Service\Module\WebShop\External\CheckOut\Component\OrderHeaderDTOCreator: ~
  App\Service\Module\WebShop\External\CheckOut\Component\OrderItemDTOCreator: ~
  App\Service\Module\WebShop\External\CheckOut\Component\OrderAddressDTOCreator: ~
  App\Service\Module\WebShop\External\Order\OrderToCart: ~
  App\Service\Module\WebShop\External\Cart\Session\Object\CartSessionObject: ~

  App\Service\Module\WebShop\External\Cart\Session\CartSessionProductService: ~
  App\Service\Module\WebShop\External\Payment\PaymentService: ~
  App\Service\Module\WebShop\External\Payment\PaymentPriceCalculator: ~
  App\Service\Module\WebShop\External\Address\CheckoutAddressChooseParser: ~
  App\Service\Module\WebShop\External\Address\CheckOutAddressSession: ~
  App\Service\Module\WebShop\External\Address\CheckOutAddressQuery: ~
  App\Service\Module\WebShop\External\Address\CheckOutAddressSave: ~
  App\Service\MasterData\Product\ProductSearch: ~
  App\Service\MasterData\Product\Image\ProductImageOperation: ~
  App\Service\MasterData\Product\Image\Provider\ProductDirectoryPathProvider: ~
  App\Service\MasterData\Product\Image\Provider\ProductDirectoryImagePathProvider: ~
  App\Service\MasterData\Product\ProductService: ~
  App\Service\MasterData\Price\PriceByCountryCalculator: ~
  App\Service\MasterData\Price\PriceCalculator: ~
  App\Service\MasterData\Category\Image\CategoryImageOperation: ~
  App\Service\MasterData\Category\Image\Provider\CategoryDirectoryPathProvider: ~
  App\Service\MasterData\Category\Image\Provider\CategoryDirectoryImagePathProvider: ~
  App\Service\MasterData\Category\PathCalculator: ~
  App\Service\MasterData\Customer\Address\CustomerAddressSave: ~
  App\Service\MasterData\Customer\Address\CustomerAddressQuery: ~
  App\Service\Testing\SessionHelper: ~
  App\Service\Testing\AbstractDoctrineWithMigrationTestCase: ~
  App\Service\Twig\MasterData\Customer\GetAddressInSingleLine: ~
  App\Service\Twig\Security\IsUserACustomer: ~
  App\Service\Twig\RemovePublicPathService: ~
  App\Service\Twig\EventDispatcher\GridCreateLinkEventDispatcher: ~
  App\Service\Twig\EventDispatcher\GridColumnEventDispatcher: ~
  App\Service\Common\Image\SystemImage: ~
  App\Service\Common\List\ListGridConfig: ~
  App\Service\Common\List\CreateButtonConfig: ~
  App\Service\Common\List\Column\ListGridColumn: ~
  App\Service\Common\Email\EmailService: ~
  App\Service\Common\File\Base\AbstractFileDirectoryPathProvider: ~
  App\Service\Common\File\FilePhysicalOperation: ~
  App\Service\Common\File\Provider\Interfaces\DirectoryPathProviderInterface: ~
  App\Service\Common\File\Provider\FileDirectoryPathProvider: ~
  App\Service\Security\User\Employee\EmployeeFromUserFinder: ~
  App\Service\Security\User\Customer\CustomerService: ~
  App\Service\Security\User\Customer\CustomerFromUserFinder: ~
  App\Service\Component\Controller\RequestStackHelper: ~
  App\Service\Component\Controller\HttpKernelHelper: ~
  App\Service\Component\Controller\ViewHelper: ~
  App\Service\Component\Routing\RoutingConstants: ~
  App\Service\Component\UI\Search\SearchEntityInterface: ~
  App\Service\Component\UI\Panel\Components\PanelHeadController: ~
  App\Service\Component\UI\Panel\Components\PanelFooterController: ~
  App\Service\Component\UI\Panel\Components\PanelSideBarController: ~
  App\Service\Component\UI\Panel\Components\PanelContentController: ~
  App\Service\Component\UI\Panel\Components\PanelHeaderController: ~
  App\Service\Component\UI\Panel\Session\SessionAndMethodChecker: ~
  App\Service\Component\UI\Panel\PanelMainController: ~
  App\Service\Component\JsonDecode: ~
  App\Security\UserProvider: ~


  App\Controller\Admin\System\SettingsController: ~

  App\Controller\Admin\Employee\FrameWork\SideBarController: ~
  App\Controller\Admin\Employee\FrameWork\HeaderController: ~
  App\Controller\Admin\Employee\FrameWork\Event\BeforePanelMainForwarding: ~
  App\Controller\Admin\Employee\FrameWork\ContentController: ~
  App\Controller\Admin\Employee\FrameWork\HeadController: ~
  App\Controller\Admin\Employee\FrameWork\FooterController: ~
  App\Controller\Admin\Employee\FrameWork\MainController: ~
  App\Controller\Admin\Customer\Framework\SideBarController: ~
  App\Controller\Admin\Customer\Framework\HeaderController: ~
  App\Controller\Admin\Customer\Framework\ContentController: ~
  App\Controller\Admin\Customer\Framework\HeadController: ~
  App\Controller\Admin\Customer\Framework\FooterController: ~
  App\Controller\Admin\Customer\Framework\MainController: ~
  App\Controller\Transaction\Order\Admin\Header\OrderHeaderController: ~
  App\Controller\Transaction\Order\Admin\Item\OrderItemController: ~
  App\Controller\Module\WebShop\Admin\WebShopAdminController: ~
  App\Controller\Module\WebShop\Admin\WebShopAdminSectionController: ~
  App\Controller\Module\WebShop\Admin\File\Image\WebShopImageController: ~
  App\Controller\Module\WebShop\External\Product\ProductController: ~
  App\Controller\Module\WebShop\External\Shop\Components\SideBarController: ~
  App\Controller\Module\WebShop\External\Shop\Components\HeaderController: ~
  App\Controller\Module\WebShop\External\Shop\Components\ContentController: ~
  App\Controller\Module\WebShop\External\Shop\Components\HeadController: ~
  App\Controller\Module\WebShop\External\Shop\Components\FooterController: ~
  App\Controller\Module\WebShop\External\Shop\MainController: ~
  App\Controller\Module\WebShop\External\SignUpOrLogin\SignUpOrLoginController: ~
  App\Controller\Module\WebShop\External\CheckOut\CheckOutController: ~
  App\Controller\Module\WebShop\External\Order\OrderViewBeforePaymentController: ~
  App\Controller\Module\WebShop\External\Order\OrderConfirmationController: ~
  App\Controller\Module\WebShop\External\Cart\CartController: ~
  App\Controller\Module\WebShop\External\Payment\PaymentController: ~
  App\Controller\Module\WebShop\External\Payment\PaymentTypeController: ~
  App\Controller\Module\WebShop\External\Category\CategoryController: ~
  App\Controller\Module\WebShop\External\Address\AddressController: ~
  App\Controller\MasterData\Product\Product\ProductController: ~
  App\Controller\MasterData\Product\Image\ProductImageController: ~
  App\Controller\MasterData\Product\Image\ListObject\ProductImageObject: ~
  App\Controller\MasterData\Product\Type\ProductTypeController: ~
  App\Controller\MasterData\Product\Attribute\Value\ProductAttributeValueController: ~
  App\Controller\MasterData\Product\Attribute\ProductAttributeController: ~
  App\Controller\MasterData\Product\Attribute\ProductTypeAndAttributeController: ~
  App\Controller\MasterData\Inventory\InventoryProductController: ~
  App\Controller\MasterData\Employee\EmployeeController: ~
  App\Controller\MasterData\Price\Taxes\PriceProductTaxController: ~
  App\Controller\MasterData\Price\Base\PriceProductBaseController: ~
  App\Controller\MasterData\Price\Discount\PriceProductDiscountController: ~
  App\Controller\MasterData\Category\Image\CategoryImageController: ~
  App\Controller\MasterData\Category\Image\ListObject\CategoryImageObject: ~
  App\Controller\MasterData\Category\CategoryController: ~
  App\Controller\MasterData\Customer\Type\CustomerTypeController: ~
  App\Controller\MasterData\Customer\Type\Attribute\CustomerTypeAttributeController: ~
  App\Controller\MasterData\Customer\CustomerController: ~
  App\Controller\MasterData\Customer\Address\CustomerAddressController: ~
  App\Controller\Home\HomeController: ~
  App\Controller\Common\Utility\CommonUtility: ~
  App\Controller\Common\Admin\PaymentType\PaymentTypeController: ~
  App\Controller\Common\Identification\CommonIdentificationConstants: ~
  App\Controller\Common\File\FileController: ~
  App\Controller\Common\File\SystemImageController: ~
  App\Controller\Location\CountryController: ~
  App\Controller\Location\PostalCodeController: ~
  App\Controller\Location\StateController: ~
  App\Controller\Location\CityController: ~
  App\Controller\Security\External\Credentials\ResetPasswordController: ~
  App\Controller\Security\External\Credentials\ChangePasswordController: ~
  App\Controller\Security\External\Credentials\SignUp\SignUpController: ~
  App\Controller\Security\External\Credentials\Login\LoginManagementController: ~
  App\Controller\Component\UI\Search\SearchController: ~
  App\Controller\Finance\Tax\TaxSlabController: ~
  App\Controller\Finance\Currency\CurrencyController: ~
