services:

  Silecust\WebShop\Repository\UserRepository:
    autowire: true
    tags: [ 'doctrine.repository_service' ]
  silecust_repository_user:
    alias: Silecust\WebShop\Repository\UserRepository
  Silecust\WebShop\Repository\ProductAttributeValueRepository: ~
  Silecust\WebShop\Repository\OrderAddressRepository: ~
  Silecust\WebShop\Repository\WebShopFileRepository: ~
  Silecust\WebShop\Repository\PriceProductTaxRepository: ~
  Silecust\WebShop\Repository\EmployeeRepository: ~
  Silecust\WebShop\Repository\ProductTypeAttributeRepository: ~
  Silecust\WebShop\Repository\CustomerIndividualRepository: ~
  Silecust\WebShop\Repository\OrderShippingRepository: ~
  Silecust\WebShop\Repository\CityRepository: ~
  Silecust\WebShop\Repository\ImageRepository: ~
  Silecust\WebShop\Repository\FileRepository: ~
  Silecust\WebShop\Repository\InventoryProductRepository: ~
  Silecust\WebShop\Repository\OrderItemPaymentPriceRepository: ~
  Silecust\WebShop\Repository\OrderStatusTypeRepository: ~
  Silecust\WebShop\Repository\OrderStatusRepository: ~
  Silecust\WebShop\Repository\CategoryImageRepository: ~
  Silecust\WebShop\Repository\StateRepository: ~
  Silecust\WebShop\Repository\OrderJournalRepository: ~
  Silecust\WebShop\Repository\WebShopHomeSectionRepository: ~
  Silecust\WebShop\Repository\WebShopRepository: ~
  Silecust\WebShop\Repository\DiscountPriceProductRepository: ~
  Silecust\WebShop\Repository\OrderItemRepository: ~
  Silecust\WebShop\Repository\CustomerAddressRepository: ~
  Silecust\WebShop\Repository\OrderHeaderRepository: ~
  Silecust\WebShop\Repository\CategoryRepository: ~
  Silecust\WebShop\Repository\AddressRepository: ~
  Silecust\WebShop\Repository\DiscountPriceCategoryRepository: ~
  Silecust\WebShop\Repository\CustomerTypeAttributeRepository: ~
  Silecust\WebShop\Repository\PaymentTypeRepository: ~
  Silecust\WebShop\Repository\OrderGuidRepository: ~
  Silecust\WebShop\Repository\CurrencyRepository: ~
  Silecust\WebShop\Repository\ResetPasswordRequestRepository:
    arguments:
      - "@doctrine"
  Silecust\WebShop\Repository\CustomerRepository: ~
  Silecust\WebShop\Repository\ProductAttributeRepository: ~
  Silecust\WebShop\Repository\PostalCodeRepository: ~

  Silecust\WebShop\Repository\OrderPaymentRepository: ~
  Silecust\WebShop\Repository\SalutationRepository: ~
  Silecust\WebShop\Repository\TaxSlabRepository: ~
  Silecust\WebShop\Repository\WebShopImageTypeRepository: ~
  Silecust\WebShop\Repository\ProductRepository: ~
  Silecust\WebShop\Repository\CustomerTypeRepository: ~
  Silecust\WebShop\Repository\ProductTypeRepository: ~
  Silecust\WebShop\Repository\ProductImageRepository: ~
  Silecust\WebShop\Repository\PriceProductDiscountRepository: ~
  Silecust\WebShop\Repository\ProductAttributeTypeRepository: ~
  Silecust\WebShop\Repository\CountryRepository: ~
  Silecust\WebShop\Repository\PriceProductBaseRepository: ~
  Silecust\WebShop\Repository\WebShopImageFileRepository: ~

  Silecust\WebShop\Service\Transaction\Order\Item\ItemPriceCalculator: ~
  Silecust\WebShop\Service\MasterData\Pricing\PriceByCountryCalculator: ~

 # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones


