# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $formLoginAuthenticator: '@security.authenticator.form_login.main'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Silecust\WebShop\:
        resource: '../../../src/'
        exclude:
            - '../../../src/DependencyInjection/'
            - '../../../src/Entity/'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    item_price_calculator:
        class: Silecust\WebShop\Service\Transaction\Order\Item\ItemPriceCalculator

    price_by_country_code:
        class: Silecust\WebShop\Service\MasterData\Pricing\PriceByCountryCalculator

    Silecust\WebShop\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }


    Silecust\WebShop\Twig\Security\IsUserACustomer:
        tags:
            -{ name: twig.extension }

    Silecust\WebShop\Twig\EventDispatcher\GridColumnEventDispatcher:
        tags:
            -{ name: twig.extension }
    Silecust\WebShop\Twig\EventDispatcher\GridCreateLinkEventDispatcher:
        tags:
            -{ name: twig.extension }
when@test:
    services:
        session.storage.factory.mock_file:
            class: Silecust\WebShop\Service\Testing\Utility\MyOwnMockFileSessionStorageFactory
        session.factory:
            class: Silecust\WebShop\Service\Testing\Utility\MySessionFactory
            arguments:
                $requestStack: '@request_stack'
                $storageFactory: '@session.storage.factory.mock_file'
                $usageReporter: [ '@session_listener','onSessionUsage' ]