twig:
  globals:
    item_price_calculator: "@Silecust\\WebShop\\Service\\Transaction\\Order\\Price\\Item\\ItemPriceCalculator"
    price_by_country_code: "@Silecust\\WebShop\\Service\\MasterData\\Price\\PriceByCountryCalculator"
    header_price_calculator: "@Silecust\\WebShop\\Service\\Transaction\\Order\\Price\\Header\\HeaderPriceCalculator"
    customer_from_user_finder: "@Silecust\\WebShop\\Service\\Security\\User\\Customer\\CustomerFromUserFinder"
    customer_address_query: "@Silecust\\WebShop\\Service\\MasterData\\Customer\\Address\\CustomerAddressQuery"
    main_page_title: "%silecust.main_page.title%"
