twig:
  globals:
    item_price_calculator: "@Silecust\\WebShop\\Service\\Transaction\\Order\\Price\\Item\\ItemPriceCalculator"
    price_by_country_code: "@Silecust\\WebShop\\Service\\MasterData\\Price\\PriceByCountryCalculator"
    header_price_calculator: "@Silecust\\WebShop\\Service\\Transaction\\Order\\Price\\Header\\HeaderPriceCalculator"
