services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\Service\Component\Controller\HttpKernelHelper:
    public: true
    arguments:
      - "@request_stack"
      - "@http_kernel"

  App\Service\Component\Controller\RequestStackHelper:
    public: true
    arguments:
      - "@request_stack"
  App\Service\Component\Controller\ViewHelper:
    public: true
    arguments:
      - "@twig"

  silecust_controller_http_helper:
    alias: App\Service\Component\Controller\HttpKernelHelper
  silecust_controller_request_helper:
    alias: App\Service\Component\Controller\RequestStackHelper
  silecust_controller_view_helper:
    alias: App\Service\Component\Controller\ViewHelper
  App\Service\Component\UI\Panel\Session\SessionAndMethodChecker:
    public: true
  App\Repository\CategoryRepository:
    public: true

  App\Controller\Home\HomeController:
    public: true
    arguments:
      - "@event_dispatcher"

  App\Controller\Module\WebShop\External\Shop\MainController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Service\Component\UI\Panel\PanelMainController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Service\Component\UI\Panel\Components\PanelHeadController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Service\Component\UI\Panel\Components\PanelHeaderController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Service\Component\UI\Panel\Components\PanelContentController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Service\Component\UI\Panel\Components\PanelSidebarController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Service\Component\UI\Panel\Components\PanelFooterController:
    public: true
    arguments:
      - "@event_dispatcher"

  App\Controller\Module\WebShop\External\Shop\Components\HeadController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Controller\Module\WebShop\External\Shop\Components\HeaderController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Controller\Module\WebShop\External\Shop\Components\ContentController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Controller\Module\WebShop\External\Product\ProductController:
    public: true
    arguments:
      - "@event_dispatcher"

  App\Service\Component\UI\Panel\Components\PanelSideBarController:
    public: true
    arguments:
      - "@event_dispatcher"

  App\Controller\Module\WebShop\External\Shop\Components\SideBarController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Controller\Module\WebShop\External\Category\CategoryController:
    public: true
    arguments:
      - "@event_dispatcher"
