services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Controller\Home\HomeController:
    public: true
    arguments:
      - "@event_dispatcher"

  App\Controller\Module\WebShop\External\Shop\MainController:
    public: true
    arguments:
      - "@event_dispatcher"

  App\Controller\Module\WebShop\External\Shop\Components\HeadController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Controller\Module\WebShop\External\Shop\Components\HeaderController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Controller\Module\WebShop\External\Shop\Components\ContentController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Controller\Module\WebShop\External\Product\ProductController:
    public: true
    arguments:
      - "@event_dispatcher"


  App\Controller\Module\WebShop\External\Shop\Components\SideBarController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\Controller\Module\WebShop\External\Category\CategoryController:
    public: true
    arguments:
      - "@event_dispatcher"
  App\EventSubscriber\Module\WebShop\External\Order\Product\ProductListQuerySubscriber:
    public: true
    tags:
      - 'kernel.event_subscriber'
  App\Service\Module\WebShop\External\Product\ProductListQueryBuilder:
    public: true

  App\Service\Module\WebShop\External\Product\Twig\ProductInProductList:
    public: true


