# This file is used for web shop project

when@dev:
      parameters:
            # One level from %kernel.project_dir%
            # add slash at start
            file_storage_path: '/data/dev'
when@test:
      parameters:
            # One level from %kernel.project_dir%
            # add slash at start
            file_storage_path: '/data/test'