<?php

namespace Silecust\WebShop\Form\Security\User;

use Silecust\WebShop\Form\MasterData\Customer\CustomerCreateForm;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

/**
 * Functions are similar so for now  using the customer form
 */
class SignUpAdvancedForm extends CustomerCreateForm
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
      $builder->addEventListener(FormEvents::PRE_SET_DATA,function (FormEvent $event){
          $form = $event->getForm();
          $form->remove('middleName');
          $form->remove('givenName');

      });
        $builder->get('save')->setAttribute('label',"Sign In");

    }

    public function getBlockPrefix(): string
    {
        return 'user_sign_up_advanced_form';
    }
}